# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isFullTime',
            field=models.BooleanField(default=True),
        ),
    ]
