# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_teacher_isfulltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
