# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20160402_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassTeacher', to='tax.Teacher'),
        ),
    ]
