# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20160403_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.CharField(default='201601', max_length=6),
        ),
    ]
